server:
  port: 8083
  servlet:
    contextPath: /teaProject
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/teaproject?user=root
    driverClassName: com.mysql.cj.jdbc.Driver